source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "minimal-mistakes-jekyll"
gem "jekyll-include-cache"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-gist"
